[package]
name = "serde_examples"
version = "0.1.0"
edition = "2021"

[dependencies]
ciborium = "0.2.2"
serde = { version = "1.0.215", features = ["derive"] }
serde_cbor = "0.11.2"
serde_json = "1.0.133"
