[package]
name = "slog_example"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
slog = { version = "2.7.0", features = ["max_level_trace"] }
slog-async = "2.8.0"
slog-json = "2.6.1"
slog-term = "2.9.1"
